In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("WeatherPy_challenge.csv")
city_data_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,La Ronge,CA,2020-01-05 19:25:58,55.10,-105.30,3.20,71,5,9.17,clear sky,0.00,0.00
1,1,Baihar,IN,2020-01-05 19:25:58,22.11,80.55,52.38,65,0,1.86,clear sky,0.00,0.00
2,2,Tumannyy,IN,2020-01-05 19:25:58,22.11,80.55,52.38,65,0,1.86,clear sky,0.00,0.00
3,3,Neyshabur,IR,2020-01-05 19:25:59,36.21,58.79,35.44,93,98,8.86,light snow,0.00,0.44
4,4,East London,ZA,2020-01-05 19:25:59,-33.02,27.91,68.00,94,75,9.17,broken clouds,0.00,0.00
5,5,Saleaula,ZA,2020-01-05 19:25:59,-33.02,27.91,68.00,94,75,9.17,broken clouds,0.00,0.00
6,6,Portland,US,2020-01-05 19:25:59,43.66,-70.25,34.00,47,40,16.11,scattered clouds,0.00,0.00
7,7,Kaitangata,NZ,2020-01-05 19:25:59,-46.28,169.85,50.00,70,94,14.00,light rain,1.37,0.00
8,8,Avarua,CK,2020-01-05 19:26:00,-21.21,-159.78,80.60,88,100,9.17,light rain,0.81,0.00
9,9,Atuona,PF,2020-01-05 19:26:00,-9.80,-139.03,80.49,66,0,4.27,clear sky,0.00,0.00

In [3]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)
g_key

'AIzaSyAH87X-PI8RQfWzT8amGlKi6P3N3ONdliM'

In [4]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip?"))
max_temp = float(input("What is the maximum temperature you would like for your trip?"))
raining = float(input("Do you want it to be raining? (0=no/1=yes)  "))
snowing = float(input("Do you want it to be snowing? (0=no/1=yes)  "))

What is the minimum temperature you would like for your trip?70
What is the maximum temperature you would like for your trip?95
Do you want it to be raining? (0=no/1=yes)  0
Do you want it to be snowing? (0=no/1=yes)  0

In [5]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp) & \
                                       (city_data_df["Rain inches (last 3 hrs)"] >= raining) & \
                                       (city_data_df["Snow inches (last 3 hrs)"] == snowing)]
preferred_cities_df.head(100)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
8,8,Avarua,CK,2020-01-05 19:26:00,-21.21,-159.78,80.60,88,100,9.17,light rain,0.81,0.0
9,9,Atuona,PF,2020-01-05 19:26:00,-9.80,-139.03,80.49,66,0,4.27,clear sky,0.00,0.0
10,10,Rikitea,PF,2020-01-05 19:26:00,-23.12,-134.97,76.03,75,4,13.80,clear sky,0.00,0.0
12,12,Ponta Do Sol,BR,2020-01-05 19:26:00,-20.63,-46.00,81.46,61,59,6.58,light rain,0.44,0.0
15,15,Naze,NG,2020-01-05 19:26:01,5.43,7.07,86.00,51,0,2.24,dust,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,270,Celestun,MX,2020-01-05 19:26:49,20.87,-90.40,72.32,63,23,14.16,few clouds,0.00,0.0
274,274,Maputo,MZ,2020-01-05 19:23:33,-25.97,32.57,81.00,78,40,16.11,scattered clouds,0.00,0.0
276,276,Nazca,PE,2020-01-05 19:26:50,-14.83,-74.94,84.31,42,67,9.64,broken clouds,0.00,0.0
277,277,Sorvag,PE,2020-01-05 19:26:50,-14.83,-74.94,84.31,42,67,9.64,broken clouds,0.00,0.0
280,280,Nokaneng,BW,2020-01-05 19:26:51,-19.66,22.19,78.44,59,86,3.87,light rain,0.69,0.0

In [6]:
preferred_cities_df.count()

City_ID                     238
City                        238
Country                     237
Date                        238
Lat                         238
Lng                         238
Max Temp                    238
Humidity                    238
Cloudiness                  238
Wind Speed                  238
Weather Description         238
Rain inches (last 3 hrs)    238
Snow inches (last 3 hrs)    238
dtype: int64

In [7]:
# Create DataFrame called WeatherPy_vacation to store hotel names along with city, country, max temp, and coordinates.
WeatherPy_vacation_df = preferred_cities_df[["City", "Country","Max Temp", "Weather Description" , "Lat", "Lng"]].copy()
WeatherPy_vacation_df["Hotel Name"] = ""
WeatherPy_vacation_df.head(10)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
8,Avarua,CK,80.60,light rain,-21.21,-159.78,
9,Atuona,PF,80.49,clear sky,-9.80,-139.03,
10,Rikitea,PF,76.03,clear sky,-23.12,-134.97,
12,Ponta Do Sol,BR,81.46,light rain,-20.63,-46.00,
15,Naze,NG,86.00,dust,5.43,7.07,
16,Kapaa,US,77.00,scattered clouds,22.08,-159.32,
17,Puerto Ayora,EC,84.20,scattered clouds,-0.74,-90.35,
20,Road Town,VG,82.40,scattered clouds,18.42,-64.62,
21,Yarada,IN,75.20,mist,17.65,83.27,
22,Kavaratti,IN,80.87,clear sky,10.57,72.64,

In [8]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Set parameters to search for a hotel.
params = {"radius": 5000,"type": "lodging","key": g_key}

In [9]:
# Iterate through the DataFrame.
for index, row in WeatherPy_vacation_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

# Add the latitude and longitude to the params dictionary as values to
#   the location key.
    params["location"] = f"{lat},{lng}"

# Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
# Grab the first hotel from the results and store the name.
    try:
        WeatherPy_vacation_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [14]:
WeatherPy_vacation_df.head(15)

,City,Country,Max Temp,Weather Description,Lat,Lng,Hotel Name
8,Avarua,CK,80.60,light rain,-21.21,-159.78,Paradise Inn
9,Atuona,PF,80.49,clear sky,-9.80,-139.03,Villa Enata
10,Rikitea,PF,76.03,clear sky,-23.12,-134.97,Pension Maro'i
12,Ponta Do Sol,BR,81.46,light rain,-20.63,-46.00,Hotel Escarpas do Lago
15,Naze,NG,86.00,dust,5.43,7.07,Female Hostel C
16,Kapaa,US,77.00,scattered clouds,22.08,-159.32,Sheraton Kauai Coconut Beach Resort
17,Puerto Ayora,EC,84.20,scattered clouds,-0.74,-90.35,Finch Bay Galapagos Hotel
20,Road Town,VG,82.40,scattered clouds,18.42,-64.62,"ZINGARA 76ft Catamaran, full crew-all included"
21,Yarada,IN,75.20,mist,17.65,83.27,JV's Green Valley Beach Resort
22,Kavaratti,IN,80.87,clear sky,10.57,72.64,Hotels in Lakshadweep Islands
25,Barrow,AR,80.47,light rain,-38.31,-60.23,
26,Padilla,CO,89.60,broken clouds,3.23,-76.31,La Granadina
30,Saltillo,MX,70.00,clear sky,25.42,-100.99,City Express Saltillo Norte
32,Tadine,NC,73.53,clear sky,-21.55,167.88,
33,Butaritari,KI,85.42,light rain,3.07,172.79,Isles Sunset Lodge

In [18]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Weather Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [19]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in WeatherPy_vacation_df.iterrows()]

In [20]:
# Add a pop-up marker for each city.
locations = WeatherPy_vacation_df[["Lat", "Lng"]]
weather_description = WeatherPy_vacation_df["Weather Description"]
max_temp = WeatherPy_vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))